In [1]:
!nvidia-smi

Sat Oct 23 10:04:55 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 496.13       Driver Version: 496.13       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   49C    P8    12W /  N/A |   6112MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
from WR_LS_Denoising import WR_LS_Denoise
import numpy as np

In [3]:
X_train = np.load('Indice_BERT_X_train.npy')
Y_train = np.load('Mal_train_label.npy')
X_val = np.load('Indice_BERT_X_val.npy')
Y_val = np.load('Mal_val_label.npy')

In [4]:
import cupy as cp

In [5]:
X_train = cp.array(X_train)
Y_train = cp.array(Y_train)
X_val = cp.array(X_val)
Y_val = cp.array(Y_val)

In [6]:
import time

In [7]:
start = time.ctime(time.time())
print(start)
for i in range(len(X_train)):
    Denoised =  WR_LS_Denoise(X_train[i])
    X_train[i] = X_train[i]
    if(i%1000 == 0):
        print(i, time.ctime(time.time()))

Sat Oct 23 10:04:56 2021
0 Sat Oct 23 10:04:59 2021


In [8]:
!nvidia-smi

Sat Oct 23 10:05:46 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 496.13       Driver Version: 496.13       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   62C    P0    48W /  N/A |   6062MiB /  6144MiB |     48%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [9]:
start = time.ctime(time.time())
print(start)
for i in range(len(X_val)):
    Denoised =  WR_LS_Denoise(X_val[i])
    X_val[i] = X_val[i]
    if(i%1000 == 0):
        print(i, time.ctime(time.time()))

Sat Oct 23 10:05:46 2021
0 Sat Oct 23 10:05:46 2021


In [10]:
WR_LS_Denoised_X_train = cp.save('WR_LS_Denoised_Indice_BERT_X_train.npy',X_train)
WR_LS_Denoised_X_val = cp.save('WR_LS_Denoised_Indice_BERT_X_val.npy',X_val)

In [11]:
import cupy as cp
import numpy as np

In [12]:
ls

 Volume in drive C is Acer
 Volume Serial Number is 3818-7542

 Directory of C:\Users\phvpa\OneDrive - Amrita Vishwa Vidyapeetham\Amrita-Mtech-CEN\ProjectWork\MTech Thesis\Denoise in Code mix data\Experiments\Malyalam\Indice_BERT\1000 and 100 dataset

23-10-2021  10:05    <DIR>          .
23-10-2021  09:49    <DIR>          ..
23-10-2021  09:58    <DIR>          .ipynb_checkpoints
23-10-2021  10:04    <DIR>          __pycache__
23-10-2021  10:03            30,000 Indice_BERT.ipynb
23-10-2021  09:58            33,936 Indice_BERT_Denoised_SVM_DT_RF.ipynb
23-10-2021  10:02         3,072,128 Indice_BERT_X_train.npy
23-10-2021  10:03           307,328 Indice_BERT_X_val.npy
23-10-2021  09:17         6,268,128 Mal_train.npy
23-10-2021  09:17             8,128 Mal_train_label.npy
23-10-2021  09:17            84,128 Mal_val.npy
23-10-2021  09:17               928 Mal_val_label.npy
23-10-2021  10:05         3,072,128 WR_LS_Denoised_Indice_BERT_X_train.npy
23-10-2021  10:05           307,328 WR_L

In [13]:
X_train = np.load('WR_LS_Denoised_Indice_BERT_X_train.npy')
X_val = np.load('WR_LS_Denoised_Indice_BERT_X_val.npy')

In [15]:
Y_train = np.load('Mal_train_label.npy')
Y_val = np.load('Mal_val_label.npy')

In [16]:
# X_train = cp.asarray(X_train)
# Y_train = cp.asarray(Y_train)
# X_val = cp.asarray(X_val)
# Y_val = cp.asarray(Y_val)

In [17]:
type(X_train)

numpy.ndarray

In [18]:
X_train.shape

(1000, 768)

In [19]:
Y_train.shape

(1000,)

In [20]:
type(Y_train)

numpy.ndarray

# SVM

In [21]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report

In [22]:
svc = SVC(decision_function_shape='ovo')
svc.fit(X_train,Y_train)

SVC(decision_function_shape='ovo')

In [23]:
pred_svc = svc.predict(X_val)

In [24]:
confusion_matrix(Y_val,pred_svc)

array([[ 0, 19,  0,  0,  1],
       [ 0, 18,  0,  1,  1],
       [ 1, 18,  0,  0,  1],
       [ 1, 18,  0,  1,  0],
       [ 0, 20,  0,  0,  0]], dtype=int64)

In [25]:
print(classification_report(Y_val,pred_svc))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        20
           1       0.19      0.90      0.32        20
           2       0.00      0.00      0.00        20
           3       0.50      0.05      0.09        20
           4       0.00      0.00      0.00        20

    accuracy                           0.19       100
   macro avg       0.14      0.19      0.08       100
weighted avg       0.14      0.19      0.08       100



C:\Users\phvpa\anaconda3\envs\MuRIL\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\phvpa\anaconda3\envs\MuRIL\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\phvpa\anaconda3\envs\MuRIL\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## DecisionTree

In [26]:
from sklearn.tree import DecisionTreeClassifier

In [27]:
Dtree = DecisionTreeClassifier(criterion='entropy', random_state=10)

In [28]:
Dtree.fit(X_train,Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=10)

In [29]:
pred_Dtree = Dtree.predict(X_val)

In [30]:
confusion_matrix(Y_val,pred_Dtree)

array([[ 0,  1,  0, 19,  0],
       [ 0,  0,  2, 18,  0],
       [ 0,  0,  3, 17,  0],
       [ 0,  0,  3, 17,  0],
       [ 0,  0,  1, 19,  0]], dtype=int64)

In [31]:
print(classification_report(Y_val,pred_Dtree))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        20
           1       0.00      0.00      0.00        20
           2       0.33      0.15      0.21        20
           3       0.19      0.85      0.31        20
           4       0.00      0.00      0.00        20

    accuracy                           0.20       100
   macro avg       0.10      0.20      0.10       100
weighted avg       0.10      0.20      0.10       100



C:\Users\phvpa\anaconda3\envs\MuRIL\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\phvpa\anaconda3\envs\MuRIL\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\phvpa\anaconda3\envs\MuRIL\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Random Forest

In [32]:
from sklearn.ensemble import RandomForestClassifier

In [33]:
RFC = RandomForestClassifier()
RFC.fit(X_train,Y_train)

RandomForestClassifier()

In [34]:
pred_RFC = RFC.predict(X_val)

In [35]:
confusion_matrix(Y_val,pred_RFC)

array([[ 0,  1,  0,  0, 19],
       [ 0,  0,  0,  1, 19],
       [ 0,  1,  0,  0, 19],
       [ 0,  2,  0,  1, 17],
       [ 0,  0,  0,  0, 20]], dtype=int64)

In [36]:
print(classification_report(Y_val,pred_RFC))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        20
           1       0.00      0.00      0.00        20
           2       0.00      0.00      0.00        20
           3       0.50      0.05      0.09        20
           4       0.21      1.00      0.35        20

    accuracy                           0.21       100
   macro avg       0.14      0.21      0.09       100
weighted avg       0.14      0.21      0.09       100



C:\Users\phvpa\anaconda3\envs\MuRIL\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\phvpa\anaconda3\envs\MuRIL\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\phvpa\anaconda3\envs\MuRIL\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
