In [1]:
!nvidia-smi

Fri Oct 22 13:33:05 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 496.13       Driver Version: 496.13       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   53C    P0    N/A /  N/A |    121MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
from WR_LS_Denoising import WR_LS_Denoise
import numpy as np

In [3]:
X_train = np.load('Indice_BERT_X_train.npy')
Y_train = np.load('Y_train.npy')
X_val = np.load('Indice_BERT_X_val.npy')
Y_val = np.load('Y_val.npy')

In [4]:
import cupy as cp

In [5]:
X_train = cp.array(X_train)
Y_train = cp.array(Y_train)
X_val = cp.array(X_val)
Y_val = cp.array(Y_val)

In [6]:
import time

In [7]:
start = time.ctime(time.time())
print(start)
for i in range(len(X_train)):
    Denoised =  WR_LS_Denoise(X_train[i])
    X_train[i] = X_train[i]
    if(i%1000 == 0):
        print(i, time.ctime(time.time()))

Fri Oct 22 13:33:06 2021
0 Fri Oct 22 13:33:08 2021
1000 Fri Oct 22 13:33:57 2021
2000 Fri Oct 22 13:34:46 2021
3000 Fri Oct 22 13:35:35 2021
4000 Fri Oct 22 13:36:27 2021
5000 Fri Oct 22 13:37:17 2021
6000 Fri Oct 22 13:38:07 2021
7000 Fri Oct 22 13:38:57 2021
8000 Fri Oct 22 13:39:47 2021
9000 Fri Oct 22 13:40:37 2021
10000 Fri Oct 22 13:41:27 2021
11000 Fri Oct 22 13:42:20 2021
12000 Fri Oct 22 13:43:13 2021
13000 Fri Oct 22 13:44:06 2021
14000 Fri Oct 22 13:44:59 2021
15000 Fri Oct 22 13:45:52 2021


In [8]:
!nvidia-smi

Fri Oct 22 13:46:38 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 496.13       Driver Version: 496.13       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   68C    P0    44W /  N/A |    955MiB /  6144MiB |     42%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [9]:
start = time.ctime(time.time())
print(start)
for i in range(len(X_val)):
    Denoised =  WR_LS_Denoise(X_val[i])
    X_val[i] = X_val[i]
    if(i%1000 == 0):
        print(i, time.ctime(time.time()))

Fri Oct 22 13:46:38 2021
0 Fri Oct 22 13:46:38 2021
1000 Fri Oct 22 13:47:30 2021


In [16]:
WR_LS_Denoised_X_train = cp.save('WR_LS_Denoised_Indice_BERT_X_train.npy',X_train)
WR_LS_Denoised_X_val = cp.save('WR_LS_Denoised_Indice_BERT_X_val.npy',X_val)

In [17]:
import cupy as cp
import numpy as np

In [18]:
ls

 Volume in drive C is Acer
 Volume Serial Number is 3818-7542

 Directory of C:\Users\phvpa\OneDrive - Amrita Vishwa Vidyapeetham\Amrita-Mtech-CEN\ProjectWork\MTech Thesis\Denoise in Code mix data\Experiments\Malyalam\Indice_BERT

22-10-2021  14:28    <DIR>          .
22-10-2021  06:25    <DIR>          ..
22-10-2021  06:31    <DIR>          .ipynb_checkpoints
22-10-2021  13:31    <DIR>          __pycache__
22-10-2021  06:25    <DIR>          Backup
22-10-2021  14:27            25,025 Denoised_SVM_DT_RF.ipynb
22-10-2021  07:13           187,035 Indice_BERT.ipynb
22-10-2021  03:55        48,808,064 Indice_BERT_X_train.npy
22-10-2021  03:50         5,425,280 Indice_BERT_X_val.npy
22-10-2021  13:31    <DIR>          lamda=0.1
23-05-2021  09:42           268,731 Mal_sentiment_full_dev.tsv
16-06-2021  04:34           287,576 Mal_sentiment_full_test_withoutlabels.tsv
23-05-2021  09:41         2,382,197 Mal_sentiment_full_train.tsv
22-10-2021  14:28        48,808,064 WR_LS_Denoised_Indice_BER

In [19]:
X_train = np.load('WR_LS_Denoised_Indice_BERT_X_train.npy')
X_val = np.load('WR_LS_Denoised_Indice_BERT_X_val.npy')

In [20]:
Y_train = np.load('Y_train.npy')
Y_val = np.load('Y_val.npy')

In [ ]:
# X_train = cp.asarray(X_train)
# Y_train = cp.asarray(Y_train)
# X_val = cp.asarray(X_val)
# Y_val = cp.asarray(Y_val)

In [21]:
type(X_train)

numpy.ndarray

In [22]:
X_train.shape

(15888, 768)

In [23]:
Y_train.shape

(15888,)

In [24]:
type(Y_train)

numpy.ndarray

# SVM

In [25]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report

In [26]:
svc = SVC(decision_function_shape='ovo')
svc.fit(X_train,Y_train)

SVC(decision_function_shape='ovo')

In [27]:
pred_svc = svc.predict(X_val)

In [28]:
confusion_matrix(Y_val,pred_svc)

array([[  0,   0, 102,   0,   0],
       [  0,   0, 237,   0,   0],
       [  0,   0, 701,   0,   5],
       [  0,   0, 141,   0,   0],
       [  0,   0, 578,   0,   2]], dtype=int64)

In [29]:
print(classification_report(Y_val,pred_svc))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       102
           1       0.00      0.00      0.00       237
           2       0.40      0.99      0.57       706
           3       0.00      0.00      0.00       141
           4       0.29      0.00      0.01       580

    accuracy                           0.40      1766
   macro avg       0.14      0.20      0.12      1766
weighted avg       0.25      0.40      0.23      1766



C:\Users\phvpa\anaconda3\envs\MuRIL\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\phvpa\anaconda3\envs\MuRIL\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\phvpa\anaconda3\envs\MuRIL\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## DecisionTree

In [30]:
from sklearn.tree import DecisionTreeClassifier

In [31]:
Dtree = DecisionTreeClassifier(criterion='entropy', random_state=10)

In [32]:
Dtree.fit(X_train,Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=10)

In [33]:
pred_Dtree = Dtree.predict(X_val)

In [34]:
confusion_matrix(Y_val,pred_Dtree)

array([[  2,  10,  57,   1,  32],
       [  7,  42, 139,   1,  48],
       [ 22,  89, 370,   2, 223],
       [  3,   6,  64,   4,  64],
       [ 14,  48, 323,   8, 187]], dtype=int64)

In [35]:
print(classification_report(Y_val,pred_Dtree))

              precision    recall  f1-score   support

           0       0.04      0.02      0.03       102
           1       0.22      0.18      0.19       237
           2       0.39      0.52      0.45       706
           3       0.25      0.03      0.05       141
           4       0.34      0.32      0.33       580

    accuracy                           0.34      1766
   macro avg       0.25      0.21      0.21      1766
weighted avg       0.32      0.34      0.32      1766



## Random Forest

In [36]:
from sklearn.ensemble import RandomForestClassifier

In [37]:
RFC = RandomForestClassifier()
RFC.fit(X_train,Y_train)

RandomForestClassifier()

In [38]:
pred_RFC = RFC.predict(X_val)

In [39]:
confusion_matrix(Y_val,pred_RFC)

array([[  0,   1,  93,   0,   8],
       [  0,   2, 216,   0,  19],
       [  0,   0, 613,   1,  92],
       [  0,   0, 106,   3,  32],
       [  0,   2, 488,   2,  88]], dtype=int64)

In [40]:
print(classification_report(Y_val,pred_RFC))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       102
           1       0.40      0.01      0.02       237
           2       0.40      0.87      0.55       706
           3       0.50      0.02      0.04       141
           4       0.37      0.15      0.21       580

    accuracy                           0.40      1766
   macro avg       0.33      0.21      0.16      1766
weighted avg       0.38      0.40      0.30      1766



C:\Users\phvpa\anaconda3\envs\MuRIL\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\phvpa\anaconda3\envs\MuRIL\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\phvpa\anaconda3\envs\MuRIL\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Orginal

In [42]:
X_train = np.load('Indice_BERT_X_train.npy')
Y_train = np.load('Y_train.npy')
X_val = np.load('Indice_BERT_X_val.npy')
Y_val = np.load('Y_val.npy')

In [43]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report

In [44]:
svc = SVC(decision_function_shape='ovo')
svc.fit(X_train,Y_train)

SVC(decision_function_shape='ovo')

In [45]:
pred_svc = svc.predict(X_val)

In [46]:
confusion_matrix(Y_val,pred_svc)

array([[  0,   0, 102,   0,   0],
       [  0,   0, 237,   0,   0],
       [  0,   0, 701,   0,   5],
       [  0,   0, 141,   0,   0],
       [  0,   0, 578,   0,   2]], dtype=int64)

In [47]:
print(classification_report(Y_val,pred_svc))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       102
           1       0.00      0.00      0.00       237
           2       0.40      0.99      0.57       706
           3       0.00      0.00      0.00       141
           4       0.29      0.00      0.01       580

    accuracy                           0.40      1766
   macro avg       0.14      0.20      0.12      1766
weighted avg       0.25      0.40      0.23      1766



C:\Users\phvpa\anaconda3\envs\MuRIL\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\phvpa\anaconda3\envs\MuRIL\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\phvpa\anaconda3\envs\MuRIL\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## DecisionTree

In [48]:
from sklearn.tree import DecisionTreeClassifier

In [49]:
Dtree = DecisionTreeClassifier(criterion='entropy', random_state=10)

In [50]:
Dtree.fit(X_train,Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=10)

In [51]:
pred_Dtree = Dtree.predict(X_val)

In [52]:
confusion_matrix(Y_val,pred_Dtree)

array([[  2,  10,  57,   1,  32],
       [  7,  42, 139,   1,  48],
       [ 22,  89, 370,   2, 223],
       [  3,   6,  64,   4,  64],
       [ 14,  48, 323,   8, 187]], dtype=int64)

In [53]:
print(classification_report(Y_val,pred_Dtree))

              precision    recall  f1-score   support

           0       0.04      0.02      0.03       102
           1       0.22      0.18      0.19       237
           2       0.39      0.52      0.45       706
           3       0.25      0.03      0.05       141
           4       0.34      0.32      0.33       580

    accuracy                           0.34      1766
   macro avg       0.25      0.21      0.21      1766
weighted avg       0.32      0.34      0.32      1766



## Random Forest

In [54]:
from sklearn.ensemble import RandomForestClassifier

In [55]:
RFC = RandomForestClassifier()
RFC.fit(X_train,Y_train)

RandomForestClassifier()

In [56]:
pred_RFC = RFC.predict(X_val)

In [57]:
confusion_matrix(Y_val,pred_RFC)

array([[  0,   0,  61,   0,  41],
       [  0,   3, 151,   0,  83],
       [  0,   0, 443,   0, 263],
       [  0,   0,  78,   2,  61],
       [  0,   1, 324,   2, 253]], dtype=int64)

In [58]:
print(classification_report(Y_val,pred_RFC))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       102
           1       0.75      0.01      0.02       237
           2       0.42      0.63      0.50       706
           3       0.50      0.01      0.03       141
           4       0.36      0.44      0.40       580

    accuracy                           0.40      1766
   macro avg       0.41      0.22      0.19      1766
weighted avg       0.43      0.40      0.34      1766



C:\Users\phvpa\anaconda3\envs\MuRIL\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\phvpa\anaconda3\envs\MuRIL\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\phvpa\anaconda3\envs\MuRIL\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [59]:
!nvidia-smi

Fri Oct 22 14:47:56 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 496.13       Driver Version: 496.13       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   55C    P8    12W /  N/A |    955MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------